---

- name: template isc-dhcp-server dhcpd.conf
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
    backup: yes
  notify:
    - 'isc-dhcp-server restart'

- name: start isc-dhcp-server service
  service:
    name: '{{ isc_dhcp_server_service }}'
    state: started
